#+SETUPFILE: ./setup.org
#+OPTIONS: toc:nil
#+TITLE: Assignments
#+HUGO_MENU: :menu main :parent Asisgnments
# #+HUGO_CUSTOM_FRONT_MATTER: :banner "testbanner"
#+PROPERTY: header-args :results code

Further assignments will be posted as they are finalized. 
* COMMENT Code

#+begin_src emacs-lisp :results table raw
(org-lms-get-grading-standards)
#+end_src

#+RESULTS:
| 83085 | #+ORG_LMS_COURSEID: 83085 | AODA Training Module 3                                    |
| 71671 | #+ORG_LMS_COURSEID: 71671 | HIS393H1 S LEC0101 20191:Digital History                  |
| 35724 | #+ORG_LMS_COURSEID: 35724 | Matthew Price's Sandbox                                   |
| 64706 | #+ORG_LMS_COURSEID: 64706 | NEW271H1 F LEC0201 20189:Interdisciplinary Special Topics |

* COMMENT Ideas <2017-04-04 Tue>                                   :noexport:
- make assignments 2,3,4 into a single website. Students can customize as they move along, and
- if they want it can be hosted on shimano for up to say 2 years.
- need to figure out access, etc. Optionally they can als ohost on gh-pages but I think maybe not if they need to load or execute js
- 

* COMMENT List                                                                :TOC_1:
:PROPERTIES:
:EXPORT_FILE_NAME: list
:END:
-  [[#participation][Participation]]
- [[#assignment-00-your-class-profile][Assignment 00: Your Class Profile]]
- [[#assignment-01-zero-to-blog-post][Assignment 01: Zero to Blog Post]]
- [[#assignment-02-javascript-basics][Assignment 02: Javascript Basics]]
- [[#assignment-03-dom-and-data][Assignment 03: DOM and Data]]
- [[#assignment-04-spatial-history][Assignment 04: Spatial History]]
- [[#assignment-05-oral-history][Assignment 05: Oral History]]
- [[#assignment-06-project-proposal][Assignment 06: Project Proposal]]

*  Participation
:PROPERTIES:
:POSTID:   174
:ID:       
:POST_DATE: [2015-12-11 Fri 11:16]
:EXPORT_FILE_NAME: participation
:END:
As described in the syllabus, I use your participation mark to determine the "-/null/+" part of your grade.  Let me explain a little more explicitly how this works.  

** The System

It's simple.  Suppose you successfully complete all the main assignments, but decide not to write a Project Proposal. Congratulations! You have qualified for a B. But what kind of a B?

| If your class participation was: | You get a: | Which ROSI will show as: |
|----------------------------------+------------+--------------------------|
| Poor                             | B-         |                       72 |
| Satisfactory                     | B          |                       75 |
| Excellent                        | B+         |                       78 |

Similarly, perhaps you were only able to complete the Git & Github, HTML & CSS, Javascript and Oral History. Oops! You're going to get a C.  Like your somewhat happier classmate, your final grade will be assigned thus:

| If your class participation was: | You get a: | Which ROSI will show as: |
|----------------------------------+------------+--------------------------|
| Poor                             | C-         |                       62 |
| Satisfactory                     | C          |                       65 |
| Excellent                        | C+         |                       68 |

*But Note!*

A+ is a special grade.  Suppose you complete all the assignments satisfactorily, *including the additional "A only" sections of the relevant assignments*.  Wow! You get an A, great.  But...  do you get an A+?

| If your class participation was: | You get an: | Which ROSI will show as: |
|----------------------------------+-------------+--------------------------|
| Poor                             | A-          |                       83 |
| Satisfactory                     | A           |                       88 |
| Excellent                        | DEPENDS     |                  DEPENDS |

Even if your participation was excellent, you will only receive an A+ if your work was consistently excellent and occasionally brilliant.  So, if you successfully complete all the assignments (great!), and also are a great class participant (thanks!), then I'll look over all your work and make a value judgment about whether you deserve this rare and precious grade.

*Final Note for 2018* -- this year, there isn't really a "D" grade. To pass the course you basically have to get a C. In rare cases I will consider lowering the grading criteria for the "Oral History" assignment to permit a student to scrape through the course.  

** Participation Criteria
Your participation mark is a combination of /in-class/ and /online/ participation.  

*** In the Classroom
But what makes for good class participation?  You might want to start by reading [[http://wcm1.web.rice.edu/howtodiscuss.html][How to discuss a book for history]], which has lots of helpful suggestions. Really, please read it -- it's illuminating. But, meanwhile, here are some hints:

- Show up for class :: It's hard to discuss when you're not here.
- Do the Readings :: It's hard to discuss what you haven't read.  I will try hard not to assign too much reading; in return, please try to read it.
- Be Courteous :: Treat your classmates with respect, even when your opinions differ fiercely.  Refrain from interrupting others, notice when others have been waiting & let them speak first, and so on. Don't shut other people down, and frame your comments in a way that invites further discussion.
- Listen :: Pay careful attention when your classmates are speaking; if their ideas seem a little unclear, try to fill in the gaps, either by thinking silently, or by asking friendly, clarifying questions.  Try to think about how their positions relate to yours, and, especially, whether you should perhaps change your mind a little based on what they have to say.
- Be Clear :: think about the readings before you come to class, so that your opinions are well-formed.
- Be Brave :: It can be intimidating to speak in class, especially if you have found the readings or the lecture confusing. But /you will almost never be alone./ If one person is confused, others likely are too.  Have the courage to speak up -- everyone in the room is likely to thank you.  If you are extremely shy in person, then come speak to me and we can try to work out a solution for you.
- Participate in Group work :: Occasionally we will break up into small groups.  The same princples apply to group work -- I'll be paying attention.  


*** Online
Our Slack workspace is also a great way to participate. Contribute to the class in Slack by asking good questions, helping out your classmates, and correcting any professorial errors from lecture!
** Finally

If you can do all of these things consistently, you're likely to earn a "+".  If you're not sure how you're doing, come ask me in a couple of weeks and I'll give you some feedback.

* Assignment 00: Your Class Profile                              :assignment:
:PROPERTIES:
:EXPORT_FILE_NAME: 00-git
:PUBLISH:  t
:DUE_AT: 2019-01-18
:GRADING_STANDARD_ID: nil
:GRADING_TYPE: pass_fail
:ASSIGNMENT_TYPE: github
:ASSIGNMENT_WEIGHT: 0.10
:CANVAS_SUBMISSION_TYPES: (online_upload)
:OL_DIRECTORY: ~/src/dh-2019-stu/00-profile2/
:END:
** General Description
If you're looking for [[https://github.com/titaniumbones/history-please][History, Please]], follow that link! Your job in this assignment is to tell the class a few things about yourself.  In the process we'll think about a few issues related to digital storage of information, including privacy, interpretation of sources, and data vs. knowledge. 

One of the hardest parts of this course for many people is setting up their working environment.  In this assignment you will be need to [[./../../tools/setup][set up your working environment]] and then use Git, much as we did in class, but this time manipulating the command line. 

This may take longer than you think, and it's due soon. Please get started soon by:
- [[https://classroom.github.com/a/isSHhGpz][clicking on this link to get your account set up]]
 following the instructions on [[https://github.com/DH2019/00-class-profile/][the Assignment 0 site]]. 

**  Rubric :rubric: 
- [ ] Passes General Tests
- [ ] Passes Reflection Tests
- *Grade* :: 
- *Comments*: 

* Assignment 01: Zero to Blog Post :assignment:
:PROPERTIES:
:POSTID:   177
:ID:       o2b:7dd9ce6e-51ba-4f8c-a641-39dc56dc121f
:EXPORT_FILE_NAME: 01-html-css
:PUBLISH:  t
:DUE_AT: 2019-01-18
:GRADING_STANDARD_ID: nil
:GRADING_TYPE: pass_fail
:ASSIGNMENT_TYPE: github
:ASSIGNMENT_WEIGHT: 0.10
:CANVAS_SUBMISSION_TYPES: (online_upload)
:OL_DIRECTORY: ~/src/dh-2019-stu/01-blog/
:BASECOMMIT: b430c3fb479420499583555911fcfc13a49527eb
:END:

*Due Date: Jan. 31* (2 days later than original deadline)
** General Description
You do not have to become a coder to do well in this course.  However, you /will/ have to be willing to explore technical skills that you might not otherwise develop as a humanities scholar.  In this second assignment, we'll use one of the web's many excellent self-education platforms to learn the very basics of how web pages work.  We'll then extend that knowledge with a set of slightly more advanced programming exercises.  

Web pages are composed of three components:  HTML, CSS, and Javascript.  HTML provides the /structure and content/ of a web page; CSS controls the /style of presentation/; and Javascript permits /dynamic modification/ of both.  To explore the web from the inside, you need to be a little bit comfortable in all three.  

In this assignment you will be introduced to HTML and CSS. The detailed assignment README leads you through a series of skill-building exercises, and provides links to comprehensive tutorial resources. As always, ask for help on Slack; use the new ~#blog-assignment~ channel for support/collaboration. 

*[[https://classroom.github.com/a/jw8eA63G][here is the assignment repo-creation link!!]]*
 
**  Rubric :rubric: 
- [ ] Passes General Tests
- [ ] Passes Reflection Tests
- *Grade* :: 
- *Comments*: 

* Assignment 02: Javascript Basics :assignment:
:PROPERTIES:
:EXPORT_FILE_NAME: 02-js-basics
:PUBLISH:  nil
:DUE_AT: 2019-02-12
:GRADING_STANDARD_ID: nil
:GRADING_TYPE: pass_fail
:ASSIGNMENT_TYPE: github
:ASSIGNMENT_WEIGHT: 0.10
:CANVAS_SUBMISSION_TYPES: (none)
:OL_DIRECTORY: ~/src/dh-2019-stu/02-javascript
:BASECOMMIT: f6c45cc2a0c57610e060cff992928d38bfe85681
:CANVASID: 137731
:CANVAS_HTML_URL: https://q.utoronto.ca/courses/71671/assignments/137731
:CANVAS_SUBMISSION_URL: https://q.utoronto.ca/courses/71671/assignments/137731/submissions?zip=1
:SUBMISSIONS_DOWNLOAD_URL: https://q.utoronto.ca/courses/71671/assignments/137731/submissions?zip=1
:END:

*Due Date: Feb 12*

This assignment introduces you to the third and most interesting pillar of basic web development: Javascript. 

Due at end of the day on the due date, you can [[https://github.com/DigitalHistory/assignment-02-javascript][find the asssignment on Github]] but please be sure to check out your own copy (as per the instructions) [[https://classroom.github.com/a/oqxwq0a3][by following this link]], and cloning the resultant repository to your laptop.  

**  Rubric                                                          :rubric: 
- [ ] Passes General Tests
- [ ] Passes Reflection Tests
- *Grade* :: 
- *Comments*: 

* Assignment 03: DOM and Data :assignment:
:PROPERTIES:
:EXPORT_FILE_NAME: 03-dom-data
:OL_PUBLISH:  t
:DUE_AT: 2019-03-01
:GRADING_STANDARD_ID: nil
:GRADING_TYPE: pass_fail
:ASSIGNMENT_TYPE: github
:ASSIGNMENT_WEIGHT: 0.10
:CANVAS_SUBMISSION_TYPES: (none)
:OL_DIRECTORY: ~/src/dh-2019-stu/03-dom-data
:BASECOMMIT: f6c45cc2a0c57610e060cff992928d38bfe85681
:CANVASID: 137730
:CANVAS_HTML_URL: https://q.utoronto.ca/courses/71671/assignments/137730
:CANVAS_SUBMISSION_URL: https://q.utoronto.ca/courses/71671/assignments/137730/submissions?zip=1
:SUBMISSIONS_DOWNLOAD_URL: https://q.utoronto.ca/courses/71671/assignments/137730/submissions?zip=1
:PUBLISH:  t
:END:

*Due Date: March 01*

In this assignment, you will slowly work your way up to manipulation of real web pages via Javascript.  This can be a difficult transition, so be prepared for some teeth-gnashing.  

Due at end of the day on the due date, you can [[https://classroom.github.com/a/_ocP1kS-][find the asssignment on Github]], and please be sure to check out your own copy (as per the instructions) by [[https://classroom.github.com/a/_ocP1kS-][following this link]], and cloning the resultant repository to your laptop.

  
**  Rubric                                                          :rubric: 
- [ ] Passes General Tests
- [ ] Passes Reflection Tests
- *Grade* :: 
- *Comments*: 

* Assignment 04: Spatial History                                 :assignment:
:PROPERTIES:
:EXPORT_FILE_NAME: 04-spatial-history
:ID:       o2b:627e464d-d361-45f6-a371-9cd74dbdc060
:PARENT:   Assignments
:OL_PUBLISH:  t
:DUE_AT: 2019-03-01
:GRADING_STANDARD_ID: nil
:GRADING_TYPE: pass_fail
:ASSIGNMENT_TYPE: github
:ASSIGNMENT_WEIGHT: 0.10
:CANVAS_SUBMISSION_TYPES: (none)
:OL_DIRECTORY: ~/src/dh-2019-stu/advanced-topics
:BASECOMMIT: f6c45cc2a0c57610e060cff992928d38bfe85681
:CANVASID: 145793
:CANVAS_HTML_URL: https://q.utoronto.ca/courses/71671/assignments/145793
:CANVAS_SUBMISSION_URL: https://q.utoronto.ca/courses/71671/assignments/145793/submissions?zip=1
:SUBMISSIONS_DOWNLOAD_URL: https://q.utoronto.ca/courses/71671/assignments/145793/submissions?zip=1
:PUBLISH:  t
:END:
*Due Date: March 18*

Your next assignment builds directly from our in-class exercise, and should be quite a bit easier to manage, technically, than your last assignment.  Essentially, you will repeat the in-class assignment with much greater intellectual effort, but using the same technical framework. [[https://classroom.github.com/a/oC6_7PJk][The assignment is now online]], and I have extended the due date to Monday, March 18.
**  Rubric                                                          :rubric: 
- [ ] Code Works
- [ ] Map is Relevant to Essay
- [ ] Essay makes relevant/significant Historical claim

- *Grade* :: 
- *Comments* :: 

* Assignment 05: Oral History                                    :assignment:
:PROPERTIES:
:PARENT:   Assignments
:ID:       o2b:38f6d843-a1b8-448c-8538-05671e4fdc06
:POSTID:   330
:POST_DATE: [2017-01-04 Wed 22:04]
:EXPORT_FILE_NAME: 05-oral-history
:OL_PUBLISH:  t
:DUE_AT: 2019-03-01
:GRADING_STANDARD_ID: nil
:GRADING_TYPE: pass_fail
:ASSIGNMENT_TYPE: github
:ASSIGNMENT_WEIGHT: 0.10
:CANVAS_SUBMISSION_TYPES: (none)
:OL_DIRECTORY: ~/src/dh-2019-stu/advanced-topics
:BASECOMMIT: f6c45cc2a0c57610e060cff992928d38bfe85681
:PUBLISH:  t
:CANVASID: 153269
:CANVAS_HTML_URL: https://q.utoronto.ca/courses/71671/assignments/153269
:CANVAS_SUBMISSION_URL: https://q.utoronto.ca/courses/71671/assignments/153269/submissions?zip=1
:SUBMISSIONS_DOWNLOAD_URL: https://q.utoronto.ca/courses/71671/assignments/153269/submissions?zip=1
:END:

 *Due Date: March 30*

There is no new assignment link for the Oral History assignment; instead, you will just use  [[https://classroom.github.com/a/oC6_7PJk][the repository you have already cloned, or follow this old link to clone for the first time]]. 


However, you will need to update some of the files in your repository to newer versions that I have since pushed to the main assignment repository.  If you followed my instructions, you will not have made any changed to these files, so it should be trivial to pull in my changes by pasting these commands into the terminal (be sure you are in the root directory of your repository when issuing these commands):
#+begin_src sh
git remote add upstream https://github.com/DigitalHistory/advanced-topics.git
git pull upstream master
#+end_src

This may pop you into a new editor window to edit the commit message.  If so, just save it as as is and close; commit should proceed from there. If you have issues, please post them to Slack.  

Some more advanced Git command tutorials coming your way soon. 

See the README.org file in your own repo or [[https://github.com/DigitalHistory/advanced-topics/tree/master/oral-history][the upstream Github Repo]] for details.


**  Rubric                                                          :rubric: 
- *Grade* :: 
- *Comments* ::  

* Assignment 06: Project Proposal :assignment:
:PROPERTIES:
:PARENT:   Assignments
:ID:       o2b:9c3ea2d8-28ce-4a11-aa3d-7513c92f93fd
:POST_DATE: [2017-03-10 Fri 13:12]
:POSTID:   629
:EXPORT_FILE_NAME: 06-project-proposal
:END:
*Due Date: April 02*

Remember that the proper way to create your assignment repository [[https://classroom.github.com/a/oC6_7PJk][is by clicking on this lick, allowing Github Classroom to do the work for you]]. (But you should already have done this for the last two assignments!) 

As before, please make sure you've pulled from the upstream repository before starting work on this assignment.  See your own repo or [[https://github.com/DigitalHistory/advanced-topics/tree/master/project-proposal][the upstream Github Repo]] for details.

**  Rubric                                                          :rubric: 
- [ ] Passes General Tests

- *Grade* :: 
- *Comments* ::  
* COMMENT Assignment 02: Distant History                         :deprecated:
:PROPERTIES:
:ID:       o2b:688604c8-31fb-4a73-9267-f85abc803838
:POSTID:   209
:PARENT: Assignments
:POST_DATE: [2015-12-14 Mon 14:03]
:EXPORT_FILE_NAME: comment-assignment-02-distant-history
:END:


*Due Date: Feb. 27*

In class we learned how to use [[http://beta.voyant.org][Voyant tools]]. If you missed class, you may want to [[http://docs.voyant-tools.org/workshops/dh2015/][read this excellent tutorial]].

In this assignment, you will
- create/choose a corpus for voyant tools
- devise a set of questions you want to ask using voyant
- do your best to answer those questions
- write a report on this activity
In what follows, I lay out expectations for each of these parts in turn. 

** Create or Choose A Corpus
Choose a set of texts related to a topic in which you have a genuine interest. These texts are your /primary sources/; so, if you choose a set of scholarly articles, then you will be investigating /the history of scholarship/ rather than /the history of the object of scholarship/. That's fine, but be aware of what you're doing. 

Actually finding the texts you want, and getting them into the right format, can be quite challenging.  I have already created a few corpora on the http://hackinghistory.ca:8888 Voyant tools server, and you may want to look at them first.  They include:
- [[http://shimano:8888/?corpus=95a7a99e6bc7a1414f4b34a00fa6df72][Shakespeare's Plays]]
- [[http://shimano:8888/?corpus=ce4b80c8f92d5b97695d3bc1242c57f7][Austen's Novels]]
- A collection of [[http://shimano:8888/?corpus=aa1dd38843c3c9af47f1a7cbca994d4f][Abraham Lincoln's Speeches]]
- All of the [[http://shimano:8888/?corpus=29104c8270a99073de565713ffa5ec01][Inaugural Speeches of US Presidents]]
- [[http://shimano:8888/?corpus=22415bf68910b41a4a807324544873b3][A collection of Sunday Schoolbooks from the Nineteenth Century]], copied from [[http://www.lib.msu.edu/ssbdata/][here]]
- The full archive of the [[http://archive.lib.msu.edu/dinfo/grange_visitor/][Grange Visitor]], a periodical of the Grange movement

If you are absolutely stuck for texts, you may want to use one of these sources (I may add more over the next week, so keep checking back).  

I have also written a script that will collect and download large numbers of texts from [[http://archive.org][the Internet Archive]].  I am hoping to implement it in a form that you can use yourselves, but for the present, I encourage you to use the [[https://archive.org/advancedsearch.php][Advanced Search Form]] on the Archive website to assemble a suitable corpus of texts. Once you are satisfied with your search (and you will likely need to modify your search many times!), send me an email with the text of your query (it will look like ~title:(physiology) AND collection:(medicalheritagelibrary) AND date:[1800-01-01 TO 1900-01-01]~, and will be displayed in the search results).  

(Alternatively, and preferably, you can follow the "Help with CSV" instructions on the search page and create a CSV file with *at least* the identifier, year, title, and author fields. Then send me that file.)

There are many other ways to assemble a corpus, and there are large numbers of corpora already available on line. However, many of these are not immediately suitable for working with Yovant Tools, so you may find yourself in for a fair amount of work if you choose thatroute.  

When you choose your texts, you are perforce in part determining the kinds of questions you can ask, so please do so carefully. 

Textual analysis works best with a substantial corpus of texts; not 2 or 3, but 10 or 100 or 1000. And it also works best with a carefully chosen corpus -- text that have some relationship to each other. It is the nature of this relationship that you will investigate in this assignment.

** Set some Questions
Write down a list of at least 5 questions that you want to ask of these texts.  They should be historically relevant questions, the answers to which will inform your view of a real historical phenomenon.

** Perform the Analysis.
Perform several analyses of your corpus using the Voyant tools. In all likelihood, you will want to use:
- scoping tools, to create graphs/wordles for both corpora and individual texts;
- wordle to give an impression of your data;
- trends to show frequencies across texts;
- links or collocate to show concept maps;
- context to give insight into the /manner/ of use of words;

  When you get a view that you like, be sure to /export/ the view to a URL that you can link to in your report (see the tutorial for export instructions).

  This analysis should
  - show comprehension of the appropriate use of the tool;
  - demonstrate understanding of the historical context that informs your search
  - evidence of the findings that you discuss in your report

** Write a report
The report is a short paper 3-5 pages in length discussing the outcomes of your labour. It should include:
- Description of your corpus and why you chose it
- Your initial research questions
- Your assessment of the success of the research project: Did you learn what you set out to? Did you learn anything else? What would have made the project more successful? What would you do differently next time? DOn't be afraid to present "negative results": 

** Goals
- Demonstrate a basic understanding of the kinds of questions and analysis suited to distant reading tools
- Work with a simple, introductory-level graphical interface for distant reading.
- Learn to use the resultant visualizations to support written arguments
** Expectations
To receive credit for this assignment you are expected to:
- Assemble a coherent corpus of texts. The corpus should be: related to a particular theme that you desire to analyze; large enough to perform meaningful quantitative analysis; of real interest to you; composed of primary sources.
- Formulate research questions. They should be: appropriate to quantitative analysis; of genuine historical interest; potentially answerable (not pie-in-the-sky)
- Demonstrate use of Voyant. Your analysis should be: accessible on the web by a public URL obtained through exporting; relevant to the research questions.
- Discuss the results of your research. Your discussion should be: carefully written with a minimum of spelling and grammatical errors; well-organized; honest about how successful you were; thoughtful about the reasons for success or failure.

  If you meet all these criteria, you will get credit for the assignment!
** COMMENT Some URL's 
I run Voyant from insie ~/var/www/VoyantServer2.0-M8/~ with
 ~java -Xms2g -Xmx2g -jar VoyantServer.jar --headless=true~

I've uploaded a few corpora to my local server, e.g.:
- Sunday schoolbooks  http://shimano:8888/?corpus=22415bf68910b41a4a807324544873b3, from here: http://www.lib.msu.edu/ssbdata/
- the xml version of the feeding america corpus: http://shimano:8888/?corpus=f42206f4a31b850d49f0e2eb879fa21d from https://www.lib.msu.edu/feedingamericadata/
  - text version:
- Grange Visitor: from http://archive.lib.msu.edu/dinfo/grange_visitor/, online here; 
- Lincoln speeches
- Inaugural speeches:
- 
* COMMENT Assignment 06: Short Answer 
:PROPERTIES:
:ID:       o2b:843aa819-2f95-4e9b-bba8-c88810410d02
:POST_DATE: [2016-01-13 Wed 11:54]
:POSTID:   447
:PARENT: 171
:END:
*Due Date: April 12*

Students who have not completed the "B" level requirements will be given 24 hours to respond to a series of short answer questions; think of it as something like an open-book exam. More details will be available closer to the date.  


(let ((export-file (org-entry-get (point) "EXPORT_FILE_NAME")))
               (unless export-file
                 (org-set-property
                  "EXPORT_FILE_NAME"
                  (replace-regexp-in-string " " "_" (nth 4 (org-heading-components)))))
               )
