#+POSTID: 558
#+DATE: [2017-01-04 Wed 21:55]
#+OPTIONS: toc:t
#+TITLE: Assignments
#+PROPERTY: PARENT 171
#+Parent: 171
#+HUGO_SECTION: assignment
#+HUGO_BASE_DIR: ./dh-website/
#+HUGO_STATIC_IMAGES: images
#+HUGO_MENU: :menu main :parent Asisgnments
#+HUGO_AUTO_SET_LASTMOD: t
#+HUGO_CUSTOM_FRONT_MATTER: :banner "testbanner"
#+MACRO: ts (eval (get-ts+7))


Further assignments will be posted as they are finalized. 
* COMMENT Ideas <2017-04-04 Tue>                                   :noexport:
- make assignments 2,3,4 into a single website. Students can customize as they move along, and
- if they want it can be hosted on shimano for up to say 2 years.
- need to figure out access, etc. Optionally they can als ohost on gh-pages but I think maybe not if they need to load or execute js
- 

* COMMENT List                                                                :TOC_1:
:PROPERTIES:
:EXPORT_FILE_NAME: list
:END:
-  [[#participation][Participation]]
- [[#assignment-00-git-and-github][Assignment 00: Git and Github]]
- [[#assignment-01-html--css-self-study][Assignment 01: HTML & CSS self-study]]
- [[#assignment-02-javascript-basics][Assignment 02: Javascript Basics]]
- [[#assignment-03-spatial-history][Assignment 03: Spatial History]]
- [[#assignment-04-oral-history][Assignment 04: Oral History]]
- [[#assignment-05-project-proposal][Assignment 05: Project Proposal]]

*  Participation
:PROPERTIES:
:POSTID:   174
:ID:       
:POST_DATE: [2015-12-11 Fri 11:16]
:EXPORT_FILE_NAME: participation
:END:
As described in the syllabus, I use your participation mark to determine the "-/null/+" part of your grade.  Let me explain a little more explicitly how this works.  

** The System

It's simple.  Suppose you successfully complete the HTML Top-Up, Distant Reading, Spatial History, and Aural History assignments. Congratulations! You have qualified for a B. But what kind of a B?

| If your class participation was: | You get a: | Which ROSI will show as: |
|----------------------------------+------------+--------------------------|
| Poor                             | B-         |                       72 |
| Satisfactory                     | B          |                       75 |
| Excellent                        | B+         |                       78 |

Similarly, perhaps you were only able to complete the HTML Top-Up and the Distant Reading assignment. Oops! You're going to get a D.  Like your somewhat happier classmate, your final grade will be assigned thus:

| If your class participation was: | You get a: | Which ROSI will show as: |
|----------------------------------+------------+--------------------------|
| Poor                             | D-         |                       52 |
| Satisfactory                     | D          |                       55 |
| Excellent                        | D+         |                       58 |

*But Note!*

A+ is a special grade.  Suppose you complete all the assignments satisfactorily.  Wow! You get an A, great.  But...  do you get an A+?

| If your class participation was: | You get an: | Which ROSI will show as: |
|----------------------------------+-------------+--------------------------|
| Poor                             | A-          |                       83 |
| Satisfactory                     | A           |                       88 |
| Excellent                        | DEPENDS     |                  DEPENDS |

Even if your participation was excellent, you will only receive an A+ if your work was consistently excellent and occasionally brilliant.  So, if you successfully complete all the assignments (great!), and also are a great class participant (thanks!), then I'll look over all your work and make a value judgment about whether you deserve this rare and precious grade.

** The Criteria
This is a class about digital history, so it would be *crazy* not to have an online presence.  The course website is:

http://digital.hackinghistory.ca/

I'll post just about everything related to the class there, except for marks, which I'll do on Blackboard or by personal communication.  Your participation mark is a combination of /in-class/ and /online/ participation.  

*** In the Classroom
But what makes for good class participation?  You might want to start by reading [[http://wcm1.web.rice.edu/howtodiscuss.html][How to discuss a book for history]], which has lots of helpful suggestions. Really, please read it -- it's illuminating. But, meanwhile, here are some hints:

- Show up for class :: It's hard to discuss when you're not here.
- Do the Readings :: It's hard to discuss what you haven't read.  I will try hard not to assign too much reading; in return, please try to read it.
- Be Courteous :: Treat your classmates with respect, even when your opinions differ fiercely.  Refrain from interrupting others, notice when others have been waiting & let them speak first, and so on. Don't shut other people down, and frame your comments in a way that invites further discussion.
- Listen :: Pay careful attention when your classmates are speaking; if their ideas seem a little unclear, try to fill in the gaps, either by thinking silently, or by asking friendly, clarifying questions.  Try to think about how their positions relate to yours, and, especially, whether you should perhaps change your mind a little based on what they have to say.
- Be Clear :: think about the readings before you come to class, so that your opinions are well-formed.
- Be Brave :: It can be intimidating to speak in class, especially if you have found the readings or the lecture confusing. But /you will almost never be alone./ If one person is confused, others likely are too.  Have the courage to speak up -- everyone in the room is likely to thank you.  If you are extremely shy in person, then come speak to me and we can try to work out a solution for you.
- Participate in Group work :: Occasionally we will break up into small groups.  The same princples apply to group work -- I'll be paying attention.  


*** Online
Our Slack workspace is also a great way to participate. Contribute to the class in Slack by asking good questions, helping out your classmates, and correcting any professorial errors from lecture!
** Finally

If you can do all of these things consistently, you're likely to earn a "+".  If you're not sure how you're doing, come ask me in a couple of weeks and I'll give you some feedback.

* Assignment 00: Git and Github
:PROPERTIES:
:EXPORT_FILE_NAME: 00-git
:END:
One of the hardest parts of this course for many people is setting up their working environment.  In this assignment you will be need to set up your working environment [[./../../tools/setup]] and then use Git, much as we did in class, but this time manipulating the command line.  

This may take longer than you think, and it's due soon. Please get started soon by following the instructions on [[https://github.com/DigitalHistory/assignment-00-git-and-github][the Assignment 0 website]]. 

* Assignment 01: HTML & CSS self-study 
:PROPERTIES:
:POSTID:   177
:ID:       o2b:7dd9ce6e-51ba-4f8c-a641-39dc56dc121f
:EXPORT_FILE_NAME: 01-html-css
:END:

*Due Date: Jan. 26*

You do not have to become a coder to do well in this course.  However, you /will/ have to be willing to explore technical skills that you might not otherwise develop as a humanities scholar.  In this second assignment, we'll use one of the web's many excellent self-education platforms to learn the very basics of how web pages work.  We'll then extend that knowledge with a set of slightly more advanced programming exercises.  

Web pages are composed of three components:  HTML, CSS, and Javascript.  HTML provides the /structure and content/ of a web page; CSS controls the /style of presentation/; and Javascript permits /dynamic modification/ of both.  To explore the web from the inside, you need to be a little bit comfortable in all three.  

In this assignment you will be introduced to HTML and CSS. First you will complete the HTML & CSS course on [[https://www.codecademy.com/][Codecademy.com]].  Then you'll be asked to do a set of small problems and submit them via Github.  

** Assignment
The assignment details are listed in the [[https://github.com/DigitalHistory/assignment-01-html-css][Assignment 1 Github repository]].  Read them there and follow them carefully. Be sure to budget enough time.   
** COMMENT Alternative
Already a web hotshot? If you feel like you already know everything you need to about HTML, CSS, and Javascript, prove it to me:  
- Set up an account on [[https://github.com/][Github]].  Upload one of your completed projects there.  Send me the link so I can explore.

You can learn more about git and github [[https://try.github.io/levels/1/challenges/1][here]].  This information will come in handy later, so it's well worth your time now.  

* Assignment 02: Javascript Basics
:PROPERTIES:
:EXPORT_FILE_NAME: 02-javascript
:END:
*Due Date: Feb. 02*
* COMMENT Assignment 02: Distant History
:PROPERTIES:
:ID:       o2b:688604c8-31fb-4a73-9267-f85abc803838
:POSTID:   209
:PARENT: Assignments
:POST_DATE: [2015-12-14 Mon 14:03]
:EXPORT_FILE_NAME: comment-assignment-02-distant-history
:END:


*Due Date: Feb. 27*

In class we learned how to use [[http://beta.voyant.org][Voyant tools]]. If you missed class, you may want to [[http://docs.voyant-tools.org/workshops/dh2015/][read this excellent tutorial]].

In this assignment, you will
- create/choose a corpus for voyant tools
- devise a set of questions you want to ask using voyant
- do your best to answer those questions
- write a report on this activity
In what follows, I lay out expectations for each of these parts in turn. 

** Create or Choose A Corpus
Choose a set of texts related to a topic in which you have a genuine interest. These texts are your /primary sources/; so, if you choose a set of scholarly articles, then you will be investigating /the history of scholarship/ rather than /the history of the object of scholarship/. That's fine, but be aware of what you're doing. 

Actually finding the texts you want, and getting them into the right format, can be quite challenging.  I have already created a few corpora on the http://hackinghistory.ca:8888 Voyant tools server, and you may want to look at them first.  They include:
- [[http://shimano:8888/?corpus=95a7a99e6bc7a1414f4b34a00fa6df72][Shakespeare's Plays]]
- [[http://shimano:8888/?corpus=ce4b80c8f92d5b97695d3bc1242c57f7][Austen's Novels]]
- A collection of [[http://shimano:8888/?corpus=aa1dd38843c3c9af47f1a7cbca994d4f][Abraham Lincoln's Speeches]]
- All of the [[http://shimano:8888/?corpus=29104c8270a99073de565713ffa5ec01][Inaugural Speeches of US Presidents]]
- [[http://shimano:8888/?corpus=22415bf68910b41a4a807324544873b3][A collection of Sunday Schoolbooks from the Nineteenth Century]], copied from [[http://www.lib.msu.edu/ssbdata/][here]]
- The full archive of the [[http://archive.lib.msu.edu/dinfo/grange_visitor/][Grange Visitor]], a periodical of the Grange movement

If you are absolutely stuck for texts, you may want to use one of these sources (I may add more over the next week, so keep checking back).  

I have also written a script that will collect and download large numbers of texts from [[http://archive.org][the Internet Archive]].  I am hoping to implement it in a form that you can use yourselves, but for the present, I encourage you to use the [[https://archive.org/advancedsearch.php][Advanced Search Form]] on the Archive website to assemble a suitable corpus of texts. Once you are satisfied with your search (and you will likely need to modify your search many times!), send me an email with the text of your query (it will look like ~title:(physiology) AND collection:(medicalheritagelibrary) AND date:[1800-01-01 TO 1900-01-01]~, and will be displayed in the search results).  

(Alternatively, and preferably, you can follow the "Help with CSV" instructions on the search page and create a CSV file with *at least* the identifier, year, title, and author fields. Then send me that file.)

There are many other ways to assemble a corpus, and there are large numbers of corpora already available on line. However, many of these are not immediately suitable for working with Yovant Tools, so you may find yourself in for a fair amount of work if you choose thatroute.  

When you choose your texts, you are perforce in part determining the kinds of questions you can ask, so please do so carefully. 

Textual analysis works best with a substantial corpus of texts; not 2 or 3, but 10 or 100 or 1000. And it also works best with a carefully chosen corpus -- text that have some relationship to each other. It is the nature of this relationship that you will investigate in this assignment.

** Set some Questions
Write down a list of at least 5 questions that you want to ask of these texts.  They should be historically relevant questions, the answers to which will inform your view of a real historical phenomenon.

** Perform the Analysis.
Perform several analyses of your corpus using the Voyant tools. In all likelihood, you will want to use:
- scoping tools, to create graphs/wordles for both corpora and individual texts;
- wordle to give an impression of your data;
- trends to show frequencies across texts;
- links or collocate to show concept maps;
- context to give insight into the /manner/ of use of words;

  When you get a view that you like, be sure to /export/ the view to a URL that you can link to in your report (see the tutorial for export instructions).

  This analysis should
  - show comprehension of the appropriate use of the tool;
  - demonstrate understanding of the historical context that informs your search
  - evidence of the findings that you discuss in your report

** Write a report
The report is a short paper 3-5 pages in length discussing the outcomes of your labour. It should include:
- Description of your corpus and why you chose it
- Your initial research questions
- Your assessment of the success of the research project: Did you learn what you set out to? Did you learn anything else? What would have made the project more successful? What would you do differently next time? DOn't be afraid to present "negative results": 

** Goals
- Demonstrate a basic understanding of the kinds of questions and analysis suited to distant reading tools
- Work with a simple, introductory-level graphical interface for distant reading.
- Learn to use the resultant visualizations to support written arguments
** Expectations
To receive credit for this assignment you are expected to:
- Assemble a coherent corpus of texts. The corpus should be: related to a particular theme that you desire to analyze; large enough to perform meaningful quantitative analysis; of real interest to you; composed of primary sources.
- Formulate research questions. They should be: appropriate to quantitative analysis; of genuine historical interest; potentially answerable (not pie-in-the-sky)
- Demonstrate use of Voyant. Your analysis should be: accessible on the web by a public URL obtained through exporting; relevant to the research questions.
- Discuss the results of your research. Your discussion should be: carefully written with a minimum of spelling and grammatical errors; well-organized; honest about how successful you were; thoughtful about the reasons for success or failure.

  If you meet all these criteria, you will get credit for the assignment!
** COMMENT Some URL's 
I run Voyant from insie ~/var/www/VoyantServer2.0-M8/~ with
 ~java -Xms2g -Xmx2g -jar VoyantServer.jar --headless=true~

I've uploaded a few corpora to my local server, e.g.:
- Sunday schoolbooks  http://shimano:8888/?corpus=22415bf68910b41a4a807324544873b3, from here: http://www.lib.msu.edu/ssbdata/
- the xml version of the feeding america corpus: http://shimano:8888/?corpus=f42206f4a31b850d49f0e2eb879fa21d from https://www.lib.msu.edu/feedingamericadata/
  - text version:
- Grange Visitor: from http://archive.lib.msu.edu/dinfo/grange_visitor/, online here; 
- Lincoln speeches
- Inaugural speeches:
- 
* Assignment 03: Spatial History
:PROPERTIES:
:EXPORT_FILE_NAME: 03-spatial-history
:ID:       o2b:627e464d-d361-45f6-a371-9cd74dbdc060
:PARENT:   Assignments
:POSTID:   315
:POST_DATE: [2015-12-14 Mon 14:04]
:END:
*Due Date: March 02*

In class, we made a kind of toy Google Map out of hand-coded HTML, CSS, and Javascript.  You will remember it from the course website, from [[http://jsbin.com/jusena/10/edit?html,js,output][JSBin]], and from [[https://github.com/titaniumbones/maps-with-markdown][Github]].  

Your next assignment builds directly from that in-class exercise, and should be quite a bit easier to manage, technically, than your last assignment.  Essentially, you will repeat the in-class assignment with much greater intellectual effort, but using the same technical framework. [[https://github.com/titaniumbones/maps-with-markdown][Please work directly with the files in the Github repo]], either by forking the repo, or downloading the zipball.  

** Assignment
Build a web page that includes a Google Map (complete with markers) as part of a short but substantive historical exploration of a historical topic of interest to you.  We discussed a number of such themes in the class (you should remember them from our discussion). The final product should meet the following criteria:

- Essay :: You should write a short essay, approximately 900 words (~ 3-4 pages double-spaced, if we were using word processors) addressing a small, specific historical topic /with a spatial history component/. That is, the "spatial" element shouldn't just be an afterthought, but should be at the centre of your analysis.

     Here are some plausible examples of appropriate topics:
  - Corridor of Power: Berlin's Friedrichstrasse in the Nazi Era
  - End of an Era: Toronto's last meatpacking plants
  - An Empire at Home: conservative Think Tanks in Washington, D.C.

  I just made these up, of course. You should pick something that you (a) know something about already, and (b) are interested in. Ideally, you will already have done some research into this topic, and will have a small number of sources ready to hand. The essay should introduce the reader to the topic, and make a not-too-complex argument which, again, highlights the spatial component.  ("Think tanks, so important in the construction of policy in today's United States, are a relatively new feature of American politics. In this paper, I will discuss the early history of this now-paramount institutional form, and argue that the /geographical proximity/ of these think tanks is actually an important feature.")

  You may notice that most of my examples are drawn from a kind of urban history. Urban history is obviously well-suited to spatial analysis, but there's no reason you can't describe, for instance, more widespread networks (e.g., to take some examples at random, networks of hippies, underground bus networks, comparative suffrage movements. etc.)

  Take this opportunity to think about the effect of /form/ on /content/.  How does the present of the map change the way you express your thoughts? Are new kinds of arguments possible? On the flip side, does the map lead you to ignore or downplay any important elements?

  The essay will be written in [[http://markdowntutorial.com/lesson/1/][Markdown]], which makes traditional citations a little complicated ([[http://scholdoc.scholarlymarkdown.com/][Scholarly Markdown]] solves that problem, but it's fairly difficult to set up).  So please use simple links for your citations; in Markdown, these take the form ~[I'm an inline-style link](https://www.google.com)~. So, for instance: ~[Latour, p. 97](http://search.library.utoronto.ca/details?5484640&uuid=4f41639c-43d4-45e8-81f2-d8acd9263f8a)~.  Don't worry about a bibliography.  

- Map :: Your map should have at least 5 markers, and could have many more.  You can explore more complex objects -- such as polygons -- using the geoJSON import feature sof Google Maps.  There are links to the API documentation in the code.  

     In class, we cut and paste to create multiple markers. The assignment template uses a [[http://www.w3schools.com/js/js_loop_for.asp][/for/ loop]] to /iterate/, that is, repeat, a set of actions for a group of markers.  See the template for details.  Each marker's info-window contents should contain a brief headline and some explanatory text.  Your essay should refer back to the markers, and you are free to refer to your essay in the marker text itself.

- Styling :: As was also the case with our in-class assignment, the bulk of the styling work is accomplished for us by the /strapdown.js/ script that we call at the bottom of the page. Remember that you can use any of several /bootswatch/ themes if you would like to try a different overall look. If you like, you can also customize the CSS further by using  the /style.css/ file in the project folder

** Getting your assignment, and handing it in
This assignment is stored on Github. You can get it easily by navigating to [[https://github.com/titaniumbones/maps-with-markdown]] and locating the "DownloadZIP" button. 

To hand it in, simply rezip the folder and send it to me at the Dropbox Request URL I'll send you before the due date; be sure to rename the folder itself to something that contains your name before zipping, e.g., "matt-price-his389-spatial-history". If you don't take this step, your work will not be preserved and I won't grade your assignment.  

*Or:* If you like, you are more than welcome to login to your github account, fork the repository, edit, and push your changes to the web; if you do that, then all you need to do is send me the URL of your new repository.

** Learning Objectives
- Understand what a Google Map is and how it relates to GIS
- Learn the simplest parts of the Google Maps Javascript API, and use them to create map elements
- Integrate a written historical narrative with a digital map object
** Expectations
Your essay should meet the ordinary criteria for an historical essay: clearly written, providing adequate evidence, minimal spelling and grammatical errors, etc. The relationship between topic and map should not be artificial -- the map should serve as an important part of your historical argument or explanation. 

Your Map should /work/ -- all your markers should display correctly. The initial zoom should be set so that all of your markers are visible, and when I click on those markers the appropriate text should display.  Markers should provide information that makes your written text clearer or more persuasive.  

While there is not much styling work to do, you should not create a terrible mess! You should make small visual changes to the default layout to make the legend more useful and visually appealling, and think about further work if it seems appropriate.

A "B" paper will make a convincing, interesting argument, using the map as an important and cogent support.  An "A" paper will do the same, but will do all of the above just a little bit better. "C" and "D" papers wil lbe deficient in some of these areas.  

* Assignment 04: Oral History
:PROPERTIES:
:PARENT:   Assignments
:ID:       o2b:38f6d843-a1b8-448c-8538-05671e4fdc06
:POSTID:   330
:POST_DATE: [2017-01-04 Wed 22:04]
:EXPORT_FILE_NAME: 04-oral-history
:END:

 *Due Date: March 29*

Rather than repeat myself in my usual error-prone way, I will simply direct you to the [[https://github.com/titaniumbones/oral-history-template][assignment repository on Github]]. We will discuss this at great er length in class in the final weeks of the semester. 

* Assignment 05: Project Proposal
:PROPERTIES:
:PARENT:   Assignments
:ID:       o2b:9c3ea2d8-28ce-4a11-aa3d-7513c92f93fd
:POST_DATE: [2017-03-10 Fri 13:12]
:POSTID:   629
:EXPORT_FILE_NAME: assignment-05-project-proposal
:END:
*Due Date: April 02*

For your final assignment, respond to the following /call for proposals/ with an application approximately 2000 words in length, plus a provisional budget i n the form of a spreadsheet. See below for details.

**  Call for Proposals: Digital History Initiative Grants

The Hacking History Foundation is pleased to announce a new /Digital History Initiative/, intended to advance the field of digital historical studies in Canada. We are grateful to an anonymous donor from Qatar who has agreed to underwrite three levels of grant:
- Student Development Grant :: This grant of $15,000, to be spend within a period of 12 months, funds small or preliminary projects developed by undergraduate or graduate students.
- Small Team Grant :: This grant funds up to $50,000 of work by a small team, in a period of 1-3 years.
- Large Grant :: This fund, which has no fixed upper limit of funding, funds long-term projects over a period of 3-5 years.

We invite applications for all three categories, to be submitted by <2017-04-05 Fri>. Be sure to identify the category of grant you are applying for. Regardless of the project's scale, the proposal should be:
- of genuine historical interest
- technically feasible
- appropriate to the DH methods that might be discussed e.g. in a course such as "Digital History" at the University of Toronto
- of real personal or professional interest to you, the applicant.

The Hacking History Foundation strongly values honesty. It is not necessary for you yourself to possess all the skills to complete the project; but you should be able to clearly articulate the nature of the technical challenges and have a realistic assessment of what is required to overcome them. You should also be able to articulate the /historical import/ of the project, and its worthiness for public funding, because even though we are funded by shadowy carbon-spewing billionaires, our Foundation has a strong sense of civic duty.  

** Structure
The proposal should be composed of the following elements (word lengths are approximate): 
- Introduction (500 words) :: In broad strokes, describe the project, the questions it is intended to answer, and the role of Digital History methods within the project
- Methods (500 words) :: Describe the tools you intend to use, and your plans for both research and dissemination of results
- Timeline (500 words) :: Describe the work that will be required to complete this project, and how much time you and your potential collaborators or research assistants will require to bring it to completion
- Importance (500 words) :: Discuss the importance of this research, and its place in a broader historical conversation
- Budget (1 Spreadsheet page) :: Outline and justify the costs of the project. [Note to students of Hacking History: we recognize that your costs may be, er, rough ballpark estimates. You won't be graded on the accuracy of your budget, but make a serious effort to include all the categories of cost.]

** Expectations
This is a difficult assignment. As usual, you should turn in a lucidly-written paper with minimal grammatical or spelling errors, written in accordance with scholarly standards for citation and originality.  Your project should be of genuine historical interest, and your text should convince me of that importance. Your methods section should describe the challenges inherent in the project, and provide a provisional plan for overcoming them.  You should demonstrate awareness both of the difficulties of DH research, and of the existing resources that are available to scholars undertaking this kind of work.  

/If you wish, you may certainly build upon other work you have done this semester./

Good luck! I look forward to the results.

* COMMENT Assignment 06: Short Answer 
:PROPERTIES:
:ID:       o2b:843aa819-2f95-4e9b-bba8-c88810410d02
:POST_DATE: [2016-01-13 Wed 11:54]
:POSTID:   447
:PARENT: 171
:END:
*Due Date: April 12*

Students who have not completed the "B" level requirements will be given 24 hours to respond to a series of short answer questions; think of it as something like an open-book exam. More details will be available closer to the date.  


(let ((export-file (org-entry-get (point) "EXPORT_FILE_NAME")))
               (unless export-file
                 (org-set-property
                  "EXPORT_FILE_NAME"
                  (replace-regexp-in-string " " "_" (nth 4 (org-heading-components)))))
               )
